# Thong tin co ban
title: "Tran Quoc Dat"
name: "Tran Quoc Dat"
description: "Sinh vien nganh Cong Nghe IoT - PTIT"
url: "https://Kaomine.github.io"

# Thong tin tac gia (tim phan author:)
author:
  name: "Tran Quoc Dat"
  bio: "Sinh vien nganh Cong Nghe IoT - PTIT"
  location: "TP. Ho Chi Minh"
  email: "dattran01674158329@gmail.com"
  uri: "https://Kaomine.github.io"
  github: "Kaomine"
  avatar: "profile.png"